project:
  type: book

book:
  title: "Lectures"
  author: "Prof. Dr. Markus LÃ¶cher"
  date: "05/28/2023"
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - IntroCoding_Lecture0.ipynb
    - IntroCoding_Lecture1.ipynb
    - IntroCoding_Lecture2.ipynb
    - IntroCoding_Lecture3.ipynb
    - IntroCoding_Lecture4.ipynb
    - IntroCoding_Lecture5.ipynb
    - IntroCoding_Lecture6.ipynb
    - IntroCoding_Lecture7.ipynb
    - IntroCoding_Lecture8.ipynb
    - IntroCoding_Lecture9.ipynb

format:
  html:
    theme: cosmo
    number-depth: 1
    number-sections: true

  pdf:
    documentclass: scrreprt



